-- A FUNCTION IS USED TO MANIPULATE, CLEAN , TRANSFORM, ANALYZE DATA --
-- IT IS A BUILT IN CODE THAT TAKES AN INPUT VALUE , PROCESSES IT AND GIVES AN OUTPUT --

-- THERE ARE TWO TYPES OF FUNCTIONS:- --
-- 1) SINGLE-ROW FUNCTION :- WORKS ON A SINGLE ROW --
-- 2) MULTI-ROW FUNCTIONS :- WORKS ON MULTIPLE ROWS --