-- FUNCTIONS THAT ARE USE TO MANIPULATE NUMERIC DATA --
-- HERE ARE THE MOST IMP NUMBER FUNCTIONS --

-- ABS() :- RETURN ABSOLUTE POSITIVE VALUE --
SELECT
   ABS(-100)


-- ROUND():- ROUND TO SPECIFIC DECIMA PLACES --
SELECT 
   ROUND(3.156,2),
   ROUND(3.156,1),
   ROUND(3.156,0)

-- CEILING() :- ROUND UP TO NEAREST INTEGER --
SELECT 
   CEILING(3.156)

-- FLOOR() :- ROUNDS DOWN TO NEAREST INTEGER --
SELECT
   FLOOR(4.68)

-- POWER(x,y) :- RAISES X TO THE POWER Y --
SELECT
   POWER(4,2)

-- SQRT() :- RETURN SQUARE ROOT OF A NUMBER --
SELECT
   SQRT(32)

-- SQUARE() :- RETURN SQUARE OF A NUMBER --
SELECT 
   SQUARE(7)

-- SIGN() :- RETURN SIGN OF A NUMBER (-1,0,1) --
SELECT
    SIGN(-10)

-- RAND() :- RETURN RANDOM NUMBER (0-1) --
SELECT
    RAND()


-- PI() :- RETURN VALUE OF PI --
SELECT
   PI()