-- SQL CLAUSES ARE BUILT IN FUNCTIONS THAT DEFINE SPECIFIC CONDITIONSl --

/*
TYPES OF CLAUSES IN SQL
1) WHERE
2) ORDER BY
3) GROUP BY
4) HAVING
5) DISTINCT
6) TOP
*/

-- SELECTING OUR DATABASE FIRST --
USE InternAreaDB;


-- WRITE A QUERY TO DISPLAY ALL THE DATA OF TABLE 'STUDENTS' --
SELECT 
* 
FROM students;

-- WRITE A QUERY TO DISPLAY SPECIFIC COLUMN FROM TABLE 'STUDENTS' --
SELECT 
student_id,
first_name 
FROM students


-- WHERE CLAUSE IS USED TO RETRIEVE DATA OR FILTER DATA IN BASES OF CONDITION --
-- WRITE A QUERY TO DISPLAY STUDENTS ENROLLED IN MONTH OF JUNE --
SELECT
*
FROM students
WHERE enrollment_date >= '2024-06-01' AND enrollment_date < '2024-07-01';

-- WRITE A QUERY TO FIND STUDENTS HAVING SURNAME 'VERMA' --
SELECT
* 
FROM students
WHERE last_name = 'VERMA'

-- ORDER BY CLAUSE IS USED TO SORT DATA EITHE RIN ASCENDING OR DESCENDING ORDER --
-- WRITE A QUERY TO ARRANGE STUDENTS FIRST NAME IN ASCENDING ORDER --
SELECT
*
FROM students
ORDER BY first_name ASC;

-- GROUP BY CLAUSE IS USED TO GROUP RECORDS WITH THE SAME VALUE --
-- WRITE A QUERY TO FIND HOW MANY NUMBER OF STUDENTS HAVING SAME SURNAME --
SELECT 
last_name,
COUNT(first_name) AS no_of_st
FROM students
GROUP BY last_name
ORDER BY last_name DESC;

-- HAVING CLAUSE IS USED TO FILTER THE AGGREGRATED DATA USED AFTER GROUP BY --
-- WRITE A QUERY TO DISPLAY HOW MANY STUDENTS HAVING SAME SURNAME WHOSE COUNT IS GRATER THAN 1 --
SELECT
last_name,
COUNT(first_name) AS no_of_st
FROM students
GROUP BY last_name
HAVING COUNT(first_name) > 1;

-- DISTINCT CLAUSE IS USED TO REMOVE DUPLICATE ENTRIES (USE DISTINCT ONLY WHEN NECESSARY AS IT SLOW DOWN YOUR QUERY) --
-- WRITE A QUERY TO DISPLAY LIST OF UNIQUE LAST NAME --
SELECT DISTINCT
last_name
FROM students;

-- TOP CLAUSE IS USED TO LIMIT YOUR DATA --
-- WRITE A QUERY TO DISPLAY TOP 3 STUDENTS --
SELECT TOP 3
*
FROM students;

-- WRITE A QUERY TO DISPLAY TOP 2 STUDENTS THAT RECENTLY JOINED --
SELECT TOP 2
*
FROM students
ORDER BY enrollment_date DESC;

