/*
DDL :- DATA DEFINATION LANGUAGE
IN SQL, DDL COMMAND IS USED TO DEFINE STRUCTURE OF THE TABLE IN OUR DATABASE...
WE HAVE 3 COMMANDS IN DDL:-
1) CREATE :- CREATE COMMAND IS USED TO CREATE THE TABLE
2) ALTER :- ALTER COMMAND IS USED TO MANIPULATE THE CONTENTS OR COLUMN OF THE TABLE
3) DROP :- DROP COMMAND IS USED TO DELETE THE TABLE
*/

-- SELECTING OUR DATABASE FIRST --
USE InternAreaDB;

-- CREATING A NEW TABLE CALLED 'PERSONS' --
CREATE TABLE persons
(
id INT PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL,
ph_number INT NOT NULL
);

-- MANIPULATING THE TABLE 'PERSONS' --

-- ADDING A COLUMN 'ADDRESS' --

ALTER TABLE persons 
ADD address VARCHAR(100);

-- DELETING A COLUMN 'ADDRESS' --

ALTER TABLE persons
DROP COLUMN address;

-- DELETING A TABLE --
DROP TABLE persons;