/*
DML:- DATA MANIPULATION LANGUAGE IS USED TO MODIFY OR MANIPULATE DATA
IT CONSIST OF FOLLOWING:-
1) INSERT
2) UPDATE
3) DROP OR TRUNCATE
*/
-- SELECTING OUR DATABASE FIRST --
USE InternAreaDB;

-- INSERT IS USED TO ADD DATA IN A TABLE --
INSERT INTO persons
VALUES
(1 , 'Vansh' , '9773575346'),
(2 , 'Chirag' , '9266674532');

-- QUERY TO INSERT DATA OF ANOTHER TABLE TO ANOTHER TABLE --
INSERT INTO persons
SELECT 
student_id,
first_name,
'NULL'
FROM students

-- UPDATE IS USED TO MODIFY THE EXISTING DATA ON A CONDITION --
UPDATE persons
SET phone = '9773575346'
WHERE id = 4;

UPDATE persons
SET phone = 'not known'
WHERE phone = '0';

-- DELETE DATA IS USED TO DELETE DATA ON A CONDITION --
DELETE FROM persons
WHERE id > 10;

-- TRUNCATE IS USED TO DELETE ALL THE DATA FROM TABLE MUCH FASTER AND EASIER --
TRUNCATE TABLE PERSONS;

